-- Rename columns and recreate table to enforce desired column order:
-- property_type, num_rooms, sq_meter
alter table public.flyttstadning
  rename column kvm to sq_meter;

alter table public.flyttstadning
  rename column objekt_typ to property_type;

alter table public.flyttstadning
  rename column antal_rum to num_rooms;

create table public.flyttstadning_reordered (
  id bigint generated by default as identity primary key,
  property_type text not null check (property_type in ('lägenhet', 'villa', 'radhus')),
  num_rooms integer not null check (num_rooms > 0),
  sq_meter numeric(7,2) not null check (sq_meter > 0),
  created_at timestamptz not null default now()
);

insert into public.flyttstadning_reordered (id, property_type, num_rooms, sq_meter, created_at)
select id, property_type, num_rooms, sq_meter, created_at
from public.flyttstadning;

drop table public.flyttstadning;

alter table public.flyttstadning_reordered
  rename to flyttstadning;
